language: python
python:
  - "2.7"
# command to install dependencies
install:  
  - pip install -r ProdirectScraper/requirements.txt
  - pip install coveralls
# command to run tests
before_script: cd ProdirectScraper
script:
  - python -m tests.test_helpers 
after_success:
  - coveralls
