language: python
python:
  - "2.7"
# command to install dependencies
install:  
  - pip install -r ProdirectScraper/requirements.txt
  - pip install pytest
  - pip install coveralls
# command to run tests
before_script: cd ProdirectScraper
script:
  - py.test -v --color=yes --exitfirst --showlocals --durations=5
  - python -m tests.test_helpers.py
after_success:
  - coveralls
